// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function w(){function h(){var c=this.id;"menu2"==c?(d("menu-dnt"),w()):q!=c&&(u.querySelector("#"+q).className="nav",this.className="nav act",window.localStorage.bamenu=q=c,f(c))}function f(c){var a,e=u.querySelector("#box");"menu0"==c?a=[3,"blue","home.png",0,3,"blue","options.png",1,3,"blue","feedback.png",2,3,"blue","help.png",4,0,"blue","plugins.png",5,3,"blue","security.png",3,0,"blue","history.png",6,0,"blue","fcb32.png",8,0,"blue","youtube32.png",9,0,"blue","gpl32.png",10,0,"blue",
"rate32.png",11]:"menu1"==c&&(a=[3,"red","popular.png",0,3,"red","music.png",1,3,"red","trending.png",2,3,"red","sports.png",3,3,"red","news.png",4,3,"red","gaming.png",5,0,"red","beauty.png",10,0,"red","fashion.png",11,0,"red","food.png",12,0,"red","cooking.png",13]);var b=0;c=n.i18n.getMessage(c).split(";");for(var x=document.createDocumentFragment(),p,g,d,l,f,h,k,m,q,r,t=0;t<a.length;t+=4)k=t/4,d=a[t],h=a[t+1],m=a[t+2],2==d?(l=new Uint8Array(1),crypto.getRandomValues(l),l=l[0]%h.length,k="i"+(k+
l),h=h[l],m="i/menu/"+m[l],r=c[a[t+3]+l]):(k="i"+k,m="i/menu/"+m,r=c[a[t+3]]),7>d?(q=0,p=document.createElement("div"),g=document.createElement("div"),f=document.createElement("div"),l=new Image,h="btn "+h,2<d?(h+=" wide",p.className="btnBoxWide"):p.className="btnBox",g.id=k,g.className=h,l.className="icn",f.className="txt0",l.dataset.url=l.src=m,f.textContent=r,g.appendChild(l),g.appendChild(f),p.appendChild(g),x.appendChild(p)):(d=document.createElement("div"),p=document.createElement("div"),l=
new Image,l.src=m,d.id=k,d.className="adt a"+q,l.className="icnm",p.className="txt1",p.textContent=r,d.appendChild(l),g.insertBefore(d,f),g.insertBefore(p,f),q++),b++;e.innerHTML="";e.appendChild(x);e.style.display=""}function m(c){var a=parseInt((c.target.id?c.target:c.target.parentElement).id.slice(1)),e="https://appn.center/",b="menu-";"menu0"==q?0==a?(d(b+"home"),r("https://www.chromeactions.com/",0,"https://plus.google.com/110367533603365326399/posts",0)):1==a?(d(b+"options"),r("https://www.chromeactions.com/magic-options.html",
0,"otl.html?s=6951"+(new Date).getDate()+(new Date).getHours(),0)):2==a?(d(b+"support"),r("https://www.chromeactions.com/magic-actions-for-youtube-support.html",0,"https://plus.google.com/110367533603365326399/posts",0)):3==a?(d(b+"help"),r("https://www.chromeactions.com/magic-actions-for-chrome-help-and-tips.html",0,"https://plus.google.com/110367533603365326399/posts",0)):4==a?(d(b+"plugins"),k("chrome://components")):5==a?(d(b+"ccapp"),r("https://www.hotcleaner.com/clickclean-app.html",
1,"https://myaccount.google.com/intro/privacycheckup/1",0)):6==a?(d(b+"history"),k("https://www.youtube.com/my_history")):7==a?(d(b+"fb"),k("https://www.facebook.com/magicactions")):8==a?(d(b+"yt"),k("https://www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg?sub_confirmation=1")):9==a?(d(b+"gplus"),k("https://plus.google.com/110367533603365326399/posts")):10==a&&(d(b+"rate"),k("https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif/reviews")):"menu1"==
q&&(0==a?e+="most-popular-videos":1==a?(b+="popular",e+="most-popular-music-videos"):2==a?(b+="trending",e+="trending-videos"):3==a?(b+="sports",e+="most-popular-sports-videos"):4==a?(b+="news",e+="latest-news-videos"):5==a?(b+="gaming",e+="most-popular-gaming-videos"):6==a?(b+="beauty",e+="most-popular-beauty-videos"):7==a?(b+="fashion",e+="most-popular-fashion-videos"):8==a?(b+="food",e+="most-popular-food-videos"):9==a&&(b+="cooking",e+="most-popular-cooking-videos"),d(b),k(e+".html?app=magicactions"));
c.stopPropagation()}function r(c,a,e,b){v(function(d){d?k(c,a):k(e,b)})}function k(c,a){function e(a){n.windows.update(a.windowId,{focused:!0})}n.tabs.query({url:c},function(b){if(b&&b.length)n.tabs.update(b[0].id,{active:!0},e);else if(a)try{n.windows.create({url:c,focused:!0,incognito:!0,state:"maximized"},function(){n.runtime.lastError&&n.tabs.create({url:c,active:!0},e)})}catch(x){n.tabs.create({url:c,active:!0},e)}else n.tabs.create({url:c,active:!0},e)})}function v(c){y("HEAD","https://www.chromeactions.com/",
0,"text",function(a){!a||200!=a.code&&304!=a.code?c():c(1)})}function w(){for(var c="707474682f3a2f732e77777770617970636c2e61636d2f6f62692d67776e2f69636273656d3f6372643d5f64746e616f736f6e6973627526736e6569653d7773736d6162406572746569786d746f66736d636f2e65697426615f6e6d44653d6d746e616f206f6e69206f72666961674d632041636e696f746f266e736973685f6e706970263d31676e6f75633d7279745553".match(/.{1,2}/g),a=[3,0,0,-3],e,b="",d=0,p=c.length;d<p;d++)e=a[d%4],b=d+e<p?b+String.fromCharCode(parseInt(c[d+e],16)):b+
String.fromCharCode(parseInt(c[d],16));n.tabs.create({url:b,active:!0},function(){window.close()})}function d(c){n.runtime.sendMessage(JSON.stringify({id:20,ga:{ea:c}}))}function y(c,a,d,b,f){var e={code:0},g=new XMLHttpRequest;g.open(c,a,!0);b&&(g.responseType=b);g.onload=function(a){e.code=this.status||0;e.data=this.response;f(e)};g.onerror=function(){f(e)};g.onabort=function(){f(e)};g.send(d)}var q=window.localStorage&&window.localStorage.bamenu||"menu0";(function(){var c=u,a=document.createElement("link");
a.rel="stylesheet";a.type="text/css";a.href="css/fWv.css";c.appendChild(a);var c=n.i18n.getMessage("menu").split(";"),a=document.createDocumentFragment(),e=document.createElement("div"),b=document.createElement("div");e.id="menu";b.id="box";a.appendChild(e);a.appendChild(b);for(var d=0;d<c.length;d++){var k="menu"+d;var g=document.createElement("div");g.id=k;g.className="nav";g.textContent=c[d];g.addEventListener("click",h,!1);e.appendChild(g);2==d&&(g.title="Securely via PayPal to webmaster@mixesoft.com")}u.appendChild(a);
f(q);b.addEventListener("click",m,!1);u.querySelector("#"+q).classList.add("act")})()}var u,n={},h=chrome.runtime.getURL("Qg.html");0!=top.location.href.indexOf(h)&&(top.location.href=h);for(var m in chrome)if("object"==typeof chrome[m]&&(h=Object.getOwnPropertyDescriptor(chrome,m))){n[m]=h.value;h.value={};h.configurable=!1;h.writable=!1;try{Object.defineProperty(chrome,m,h)}catch(z){n[m]=chrome[m]}}if("attachShadow"in Element.prototype){var v=Element.prototype.attachShadow;Element.prototype.attachShadow=
void 0}window.addEventListener("DOMContentLoaded",function(){var h=document.body,f;if(f=v){b:{if(navigator.appVersion&&(f=navigator.appVersion.indexOf("Chrome/"),-1<f)){f=parseInt(navigator.appVersion.slice(f+7));break b}f=0}f=53<f}u=f?v.call(h,{mode:"closed"}):h;w()},!1);window.addEventListener("blur",function(){},!1)})();
