// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function k(){document&&"complete"==document.readyState?c.c0&&(c.c4&&l(),c.c1&&document.body.addEventListener("mouseover",v,!0)):setTimeout(k,250)}function q(){var a=document.getElementById("j782k77h");if(!a){a=document.createElement("style");a.setAttribute("type","text/css");a.id="j782k77h";document.documentElement.appendChild(a);var b=a.sheet;b.disabled=c.a0&&c.a4&&c.ui?!1:!0;b.insertRule("body *{color:#909090!important}",0);b.insertRule("div,div > span{background-color:#1E1E1E!important;border-color:#333!important}",
1);b.insertRule("a{color:#656565!important}",2);b.insertRule("a:hover,a > span,div[role=button] > span{color:#6783ab!important}",3);b.insertRule("[aria-label='Posting options']{background:url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAVCAYAAACpF6WWAAAAS0lEQVQ4y2NgGAWjYIiD////t//HDqZRYijj////l6AZuPH////MlLqW7f///3uhBp74//8/F7WCgf/////b/v//Lz2aKEbBKMADAMppT6HBpHJKAAAAAElFTkSuQmCC') center no-repeat!important}",4);b.insertRule("span[role=listitem] *{color:#fff!important;background-color:transparent!important}",
5);b.insertRule("[role=checkbox],[role=tooltip] div,.Mga,.Jea{border:0!important}",6);b.insertRule("[role=checkbox] > div{border:1px solid #333!important}",7);b.insertRule("[aria-checked=true] > div{box-shadow:inset 0 0 0 3px #101010!important;background:#4e4e4e!important}",8);b.insertRule("span.r0,.g-h-f-p-Ov{background:none!important}",9);b.insertRule(".MJa,.LJa{-webkit-filter:invert(100%)!important}",10)}a.sheet.disabled=c.a0&&c.a4&&c.ui?!1:!0}function l(){d(window,"mouseover");var a=document.body.querySelector('div[role="listbox"]');
if(a){document.documentElement.style.visibility="hidden";d(a,"mouseover");d(a,"mousedown");d(a,"mouseup");if(a=document.body.querySelector('div[role="menu"]'))if(a=a.lastElementChild.firstElementChild)d(a,"mouseover"),d(a,"mousedown"),d(a,"mouseup"),d(a,"mousedown"),d(a,"mouseup");document.documentElement.style.visibility=""}else setTimeout(l,500)}function d(a,b){var r=new MouseEvent(b,{bubbles:!0,cancelable:!0,view:window});a.dispatchEvent(r)}function v(a){"img"==a.target.localName&&24<a.target.width&&
(a.target.addEventListener("mouseout",t,!1),w(a))}function w(a){e&&(e=clearTimeout(e));var b=a.target;b.removeAttribute("title");e=setTimeout(function(){var a;if((a=b)&&void 0!=a){var g=0,c=0;if(a.offsetParent){do g+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}a=[g,c]}else a=[0,0];var d=a[0];a=a[1];var e=b.offsetWidth,g=b.offsetHeight,c=b.src.replace(/s\d+-c-k/,"s256-c-k");if(300>d){var h=d+e+20;d="magic-tip-left"}else h=d-256-20,d="magic-tip-right";g=a-parseInt((256-g)/2)-5;e=128;0>g&&(e+=
g,g=0);a=h;var e=e+"px",c="url("+c+") center center/100% auto no-repeat";if(f){h=f.firstElementChild;var m=f.lastElementChild}else{f=document.createElement("div");h=document.createElement("div");m=document.createElement("iframe");f.className="magic-tip";for(var k=m,p=["scrolling","no","frameborder",0],n=0,l=p.length;n<l;n+=2)k.setAttribute(p[n],p[n+1]);f.appendChild(h);f.appendChild(m);document.body.appendChild(f)}u(f,["top",g+"px","left",a+"px","height","256px"],1);u(m,["width","256px","height",
"256px","background",c,"display","block"],1);d?(h.style.setProperty("display",""),h.className=d,e&&h.style.setProperty("top",e,"important")):h.style.setProperty("display","none","important");f.style.setProperty("display","block","important")},500);a.stopPropagation()}function t(a){a.target.removeEventListener("mouseout",t,!1);e&&(e=clearTimeout(e));f&&f.style.setProperty("display","none","important")}function u(a,b,c){if(a){var d=0,e=b.length;for(c=c?"important":null;d<e;d+=2)a.style.setProperty(b[d],
b[d+1],c)}}var c;chrome.runtime.getURL("");var f,e;chrome.runtime.sendMessage('{"id":0}',function(a){a&&a.opt&&(c=a.opt,q(),a=document.getElementById("s77n549g"),a||(a=document.createElement("style"),a.setAttribute("type","text/css"),a.id="s77n549g",document.documentElement.appendChild(a),a=a.sheet,a.insertRule(".magic-tip{z-index:2147483648;position:absolute;background-color:#333;border:7px solid #333;border-radius:7px}",0),a.insertRule(".magic-tip-right{position:absolute;top:50%;right:-17px;margin-top:-10px;width:0;height:0;border-style:solid;border-width:10px 0 10px 10px;border-color:transparent #333!important}",
1),a.insertRule(".magic-tip-left{position:absolute;top:50%;left:-17px;margin-top:-10px;width:0;height:0;border-style:solid;border-width:10px 10px 10px 0;border-color:transparent #333!important}",2),a.insertRule("a.magic-flag{width:16px;height:11px;display:inline-block;margin-right:7px;cursor:pointer;background-repeat:no-repeat}",3),a.insertRule("a.magic-flag:hover{-webkit-transform:scale(2.0)}",4)),k())});window.addEventListener("message",function(a){var b=0;try{b=JSON.parse(a.data)}catch(r){return}692==
b.id&&(c=b.opt,q())},!1)})();
